// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go
//
// Generated by this command:
//
//	mockgen -source=consumer.go -destination=mocks/consumer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCounting is a mock of Counting interface.
type MockCounting struct {
	ctrl     *gomock.Controller
	recorder *MockCountingMockRecorder
	isgomock struct{}
}

// MockCountingMockRecorder is the mock recorder for MockCounting.
type MockCountingMockRecorder struct {
	mock *MockCounting
}

// NewMockCounting creates a new mock instance.
func NewMockCounting(ctrl *gomock.Controller) *MockCounting {
	mock := &MockCounting{ctrl: ctrl}
	mock.recorder = &MockCountingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounting) EXPECT() *MockCountingMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockCounting) Count(ctx context.Context, msg domain.VoteMessage) (domain.VoteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, msg)
	ret0, _ := ret[0].(domain.VoteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockCountingMockRecorder) Count(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCounting)(nil).Count), ctx, msg)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// VoteRejected mocks base method.
func (m *MockObserver) VoteRejected(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteRejected", reason)
}

// VoteRejected indicates an expected call of VoteRejected.
func (mr *MockObserverMockRecorder) VoteRejected(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteRejected", reflect.TypeOf((*MockObserver)(nil).VoteRejected), reason)
}
