// Code generated by MockGen. DO NOT EDIT.
// Source: snapshotter.go
//
// Generated by this command:
//
//	mockgen -source=snapshotter.go -destination=mocks/snapshotter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAggregator is a mock of Aggregator interface.
type MockAggregator struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatorMockRecorder
	isgomock struct{}
}

// MockAggregatorMockRecorder is the mock recorder for MockAggregator.
type MockAggregatorMockRecorder struct {
	mock *MockAggregator
}

// NewMockAggregator creates a new mock instance.
func NewMockAggregator(ctrl *gomock.Controller) *MockAggregator {
	mock := &MockAggregator{ctrl: ctrl}
	mock.recorder = &MockAggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregator) EXPECT() *MockAggregatorMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockAggregator) Aggregate(ctx context.Context, target domain.Sharding) (domain.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, target)
	ret0, _ := ret[0].(domain.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockAggregatorMockRecorder) Aggregate(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockAggregator)(nil).Aggregate), ctx, target)
}

// MockResults is a mock of Results interface.
type MockResults struct {
	ctrl     *gomock.Controller
	recorder *MockResultsMockRecorder
	isgomock struct{}
}

// MockResultsMockRecorder is the mock recorder for MockResults.
type MockResultsMockRecorder struct {
	mock *MockResults
}

// NewMockResults creates a new mock instance.
func NewMockResults(ctrl *gomock.Controller) *MockResults {
	mock := &MockResults{ctrl: ctrl}
	mock.recorder = &MockResultsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResults) EXPECT() *MockResultsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockResults) Get(ctx context.Context, pollID uuid.UUID) (domain.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pollID)
	ret0, _ := ret[0].(domain.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResultsMockRecorder) Get(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResults)(nil).Get), ctx, pollID)
}

// Upsert mocks base method.
func (m *MockResults) Upsert(ctx context.Context, pollID uuid.UUID, a domain.Aggregate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, pollID, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockResultsMockRecorder) Upsert(ctx, pollID, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockResults)(nil).Upsert), ctx, pollID, a)
}

// MockPolls is a mock of Polls interface.
type MockPolls struct {
	ctrl     *gomock.Controller
	recorder *MockPollsMockRecorder
	isgomock struct{}
}

// MockPollsMockRecorder is the mock recorder for MockPolls.
type MockPollsMockRecorder struct {
	mock *MockPolls
}

// NewMockPolls creates a new mock instance.
func NewMockPolls(ctrl *gomock.Controller) *MockPolls {
	mock := &MockPolls{ctrl: ctrl}
	mock.recorder = &MockPollsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolls) EXPECT() *MockPollsMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockPolls) ListActive(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockPollsMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockPolls)(nil).ListActive), ctx)
}

// Transition mocks base method.
func (m *MockPolls) Transition(ctx context.Context, id uuid.UUID, to domain.Status, version uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, id, to, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transition indicates an expected call of Transition.
func (mr *MockPollsMockRecorder) Transition(ctx, id, to, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockPolls)(nil).Transition), ctx, id, to, version)
}

// MockLagReader is a mock of LagReader interface.
type MockLagReader struct {
	ctrl     *gomock.Controller
	recorder *MockLagReaderMockRecorder
	isgomock struct{}
}

// MockLagReaderMockRecorder is the mock recorder for MockLagReader.
type MockLagReaderMockRecorder struct {
	mock *MockLagReader
}

// NewMockLagReader creates a new mock instance.
func NewMockLagReader(ctrl *gomock.Controller) *MockLagReader {
	mock := &MockLagReader{ctrl: ctrl}
	mock.recorder = &MockLagReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLagReader) EXPECT() *MockLagReaderMockRecorder {
	return m.recorder
}

// Lag mocks base method.
func (m *MockLagReader) Lag(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lag", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lag indicates an expected call of Lag.
func (mr *MockLagReaderMockRecorder) Lag(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lag", reflect.TypeOf((*MockLagReader)(nil).Lag), ctx)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// SetBallots mocks base method.
func (m *MockObserver) SetBallots(pollSlug string, n int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBallots", pollSlug, n)
}

// SetBallots indicates an expected call of SetBallots.
func (mr *MockObserverMockRecorder) SetBallots(pollSlug, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBallots", reflect.TypeOf((*MockObserver)(nil).SetBallots), pollSlug, n)
}

// SetConsumerLag mocks base method.
func (m *MockObserver) SetConsumerLag(n int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConsumerLag", n)
}

// SetConsumerLag indicates an expected call of SetConsumerLag.
func (mr *MockObserverMockRecorder) SetConsumerLag(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConsumerLag", reflect.TypeOf((*MockObserver)(nil).SetConsumerLag), n)
}
