// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAdmins is a mock of Admins interface.
type MockAdmins struct {
	ctrl     *gomock.Controller
	recorder *MockAdminsMockRecorder
	isgomock struct{}
}

// MockAdminsMockRecorder is the mock recorder for MockAdmins.
type MockAdminsMockRecorder struct {
	mock *MockAdmins
}

// NewMockAdmins creates a new mock instance.
func NewMockAdmins(ctrl *gomock.Controller) *MockAdmins {
	mock := &MockAdmins{ctrl: ctrl}
	mock.recorder = &MockAdminsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmins) EXPECT() *MockAdminsMockRecorder {
	return m.recorder
}

// ByLogin mocks base method.
func (m *MockAdmins) ByLogin(ctx context.Context, login string) (*domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByLogin indicates an expected call of ByLogin.
func (mr *MockAdminsMockRecorder) ByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByLogin", reflect.TypeOf((*MockAdmins)(nil).ByLogin), ctx, login)
}
