// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mocks/admin.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"

	postgres "github.com/dubter/televote/internal/adapter/postgres"
	domain "github.com/dubter/televote/internal/domain"
)

// MockPollStore is a mock of PollStore interface.
type MockPollStore struct {
	ctrl     *gomock.Controller
	recorder *MockPollStoreMockRecorder
	isgomock struct{}
}

// MockPollStoreMockRecorder is the mock recorder for MockPollStore.
type MockPollStoreMockRecorder struct {
	mock *MockPollStore
}

// NewMockPollStore creates a new mock instance.
func NewMockPollStore(ctrl *gomock.Controller) *MockPollStore {
	mock := &MockPollStore{ctrl: ctrl}
	mock.recorder = &MockPollStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollStore) EXPECT() *MockPollStoreMockRecorder {
	return m.recorder
}

// CloseNow mocks base method.
func (m *MockPollStore) CloseNow(ctx context.Context, id uuid.UUID, version uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseNow", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseNow indicates an expected call of CloseNow.
func (mr *MockPollStoreMockRecorder) CloseNow(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseNow", reflect.TypeOf((*MockPollStore)(nil).CloseNow), ctx, id, version)
}

// Create mocks base method.
func (m *MockPollStore) Create(ctx context.Context, p *domain.Poll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPollStoreMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPollStore)(nil).Create), ctx, p)
}

// GetBySlug mocks base method.
func (m *MockPollStore) GetBySlug(ctx context.Context, slug string) (*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockPollStoreMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockPollStore)(nil).GetBySlug), ctx, slug)
}

// HasCountedVotes mocks base method.
func (m *MockPollStore) HasCountedVotes(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCountedVotes", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasCountedVotes indicates an expected call of HasCountedVotes.
func (mr *MockPollStoreMockRecorder) HasCountedVotes(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCountedVotes", reflect.TypeOf((*MockPollStore)(nil).HasCountedVotes), ctx, id)
}

// List mocks base method.
func (m *MockPollStore) List(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPollStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPollStore)(nil).List), ctx)
}

// Transition mocks base method.
func (m *MockPollStore) Transition(ctx context.Context, id uuid.UUID, to domain.Status, version uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, id, to, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transition indicates an expected call of Transition.
func (mr *MockPollStoreMockRecorder) Transition(ctx, id, to, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockPollStore)(nil).Transition), ctx, id, to, version)
}

// MockResultStore is a mock of ResultStore interface.
type MockResultStore struct {
	ctrl     *gomock.Controller
	recorder *MockResultStoreMockRecorder
	isgomock struct{}
}

// MockResultStoreMockRecorder is the mock recorder for MockResultStore.
type MockResultStoreMockRecorder struct {
	mock *MockResultStore
}

// NewMockResultStore creates a new mock instance.
func NewMockResultStore(ctrl *gomock.Controller) *MockResultStore {
	mock := &MockResultStore{ctrl: ctrl}
	mock.recorder = &MockResultStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultStore) EXPECT() *MockResultStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockResultStore) Get(ctx context.Context, pollID uuid.UUID) (domain.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pollID)
	ret0, _ := ret[0].(domain.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResultStoreMockRecorder) Get(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResultStore)(nil).Get), ctx, pollID)
}

// MockAdminStore is a mock of AdminStore interface.
type MockAdminStore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStoreMockRecorder
	isgomock struct{}
}

// MockAdminStoreMockRecorder is the mock recorder for MockAdminStore.
type MockAdminStoreMockRecorder struct {
	mock *MockAdminStore
}

// NewMockAdminStore creates a new mock instance.
func NewMockAdminStore(ctrl *gomock.Controller) *MockAdminStore {
	mock := &MockAdminStore{ctrl: ctrl}
	mock.recorder = &MockAdminStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStore) EXPECT() *MockAdminStoreMockRecorder {
	return m.recorder
}

// Audit mocks base method.
func (m *MockAdminStore) Audit(ctx context.Context, actor, action, entity string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Audit", ctx, actor, action, entity, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Audit indicates an expected call of Audit.
func (mr *MockAdminStoreMockRecorder) Audit(ctx, actor, action, entity, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Audit", reflect.TypeOf((*MockAdminStore)(nil).Audit), ctx, actor, action, entity, payload)
}

// ByLogin mocks base method.
func (m *MockAdminStore) ByLogin(ctx context.Context, login string) (*postgres.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByLogin", ctx, login)
	ret0, _ := ret[0].(*postgres.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByLogin indicates an expected call of ByLogin.
func (mr *MockAdminStoreMockRecorder) ByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByLogin", reflect.TypeOf((*MockAdminStore)(nil).ByLogin), ctx, login)
}
