receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: 'opentelemetry-collector'
          static_configs:
            - targets: ['localhost:8888']
        - job_name: 'televote'
          scrape_interval: 5s
          dns_sd_configs:
            - names: ['app-1', 'app-2', 'consumer', 'snapshot']
              type: A
              port: 8080

processors:
  batch:

exporters:
  otlphttp/metrics:
    endpoint: http://localhost:9090/api/v1/otlp
  otlphttp/traces:
    endpoint: http://localhost:4418
  otlphttp/logs:
    endpoint: http://localhost:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces]
    metrics:
      receivers: [otlp,prometheus/collector]
      processors: [batch]
      exporters: [otlphttp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
