cluster-enabled yes
cluster-config-file nodes.conf
appendonly yes
appendfsync everysec
save ""

maxmemory 512mb
maxmemory-policy noeviction

cluster-require-full-coverage no

cluster-node-timeout 5000

no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 0
