// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mocks/admin.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	auth "github.com/dubter/televote/internal/service/auth"
	polls "github.com/dubter/televote/internal/service/polls"
	gomock "go.uber.org/mock/gomock"
)

// MockPollManager is a mock of PollManager interface.
type MockPollManager struct {
	ctrl     *gomock.Controller
	recorder *MockPollManagerMockRecorder
	isgomock struct{}
}

// MockPollManagerMockRecorder is the mock recorder for MockPollManager.
type MockPollManagerMockRecorder struct {
	mock *MockPollManager
}

// NewMockPollManager creates a new mock instance.
func NewMockPollManager(ctrl *gomock.Controller) *MockPollManager {
	mock := &MockPollManager{ctrl: ctrl}
	mock.recorder = &MockPollManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollManager) EXPECT() *MockPollManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPollManager) Close(ctx context.Context, actor, slug string) (*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, actor, slug)
	ret0, _ := ret[0].(*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockPollManagerMockRecorder) Close(ctx, actor, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPollManager)(nil).Close), ctx, actor, slug)
}

// Create mocks base method.
func (m *MockPollManager) Create(ctx context.Context, actor string, spec domain.PollSpec) (*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, actor, spec)
	ret0, _ := ret[0].(*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPollManagerMockRecorder) Create(ctx, actor, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPollManager)(nil).Create), ctx, actor, spec)
}

// List mocks base method.
func (m *MockPollManager) List(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPollManagerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPollManager)(nil).List), ctx)
}

// Open mocks base method.
func (m *MockPollManager) Open(ctx context.Context, actor, slug string) (*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, actor, slug)
	ret0, _ := ret[0].(*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockPollManagerMockRecorder) Open(ctx, actor, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockPollManager)(nil).Open), ctx, actor, slug)
}

// Results mocks base method.
func (m *MockPollManager) Results(ctx context.Context, slug string) (polls.Outcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Results", ctx, slug)
	ret0, _ := ret[0].(polls.Outcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Results indicates an expected call of Results.
func (mr *MockPollManagerMockRecorder) Results(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Results", reflect.TypeOf((*MockPollManager)(nil).Results), ctx, slug)
}

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthenticator) Login(ctx context.Context, login, password string) (auth.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(auth.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticatorMockRecorder) Login(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthenticator)(nil).Login), ctx, login, password)
}

// Parse mocks base method.
func (m *MockAuthenticator) Parse(raw string) (*auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", raw)
	ret0, _ := ret[0].(*auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockAuthenticatorMockRecorder) Parse(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockAuthenticator)(nil).Parse), raw)
}
