// Code generated by MockGen. DO NOT EDIT.
// Source: capacity.go
//
// Generated by this command:
//
//	mockgen -source=capacity.go -destination=mocks/capacity.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	capacity "github.com/dubter/televote/internal/service/capacity"
	gomock "go.uber.org/mock/gomock"
)

// MockCapacityAdvisor is a mock of CapacityAdvisor interface.
type MockCapacityAdvisor struct {
	ctrl     *gomock.Controller
	recorder *MockCapacityAdvisorMockRecorder
	isgomock struct{}
}

// MockCapacityAdvisorMockRecorder is the mock recorder for MockCapacityAdvisor.
type MockCapacityAdvisorMockRecorder struct {
	mock *MockCapacityAdvisor
}

// NewMockCapacityAdvisor creates a new mock instance.
func NewMockCapacityAdvisor(ctrl *gomock.Controller) *MockCapacityAdvisor {
	mock := &MockCapacityAdvisor{ctrl: ctrl}
	mock.recorder = &MockCapacityAdvisorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapacityAdvisor) EXPECT() *MockCapacityAdvisorMockRecorder {
	return m.recorder
}

// Advise mocks base method.
func (m *MockCapacityAdvisor) Advise(ctx context.Context) (capacity.Advice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Advise", ctx)
	ret0, _ := ret[0].(capacity.Advice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Advise indicates an expected call of Advise.
func (mr *MockCapacityAdvisorMockRecorder) Advise(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advise", reflect.TypeOf((*MockCapacityAdvisor)(nil).Advise), ctx)
}
