// Code generated by MockGen. DO NOT EDIT.
// Source: public.go
//
// Generated by this command:
//
//	mockgen -source=public.go -destination=mocks/public.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pollcfg "github.com/dubter/televote/internal/service/pollcfg"
	gomock "go.uber.org/mock/gomock"
)

// MockVoting is a mock of Voting interface.
type MockVoting struct {
	ctrl     *gomock.Controller
	recorder *MockVotingMockRecorder
	isgomock struct{}
}

// MockVotingMockRecorder is the mock recorder for MockVoting.
type MockVotingMockRecorder struct {
	mock *MockVoting
}

// NewMockVoting creates a new mock instance.
func NewMockVoting(ctrl *gomock.Controller) *MockVoting {
	mock := &MockVoting{ctrl: ctrl}
	mock.recorder = &MockVotingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoting) EXPECT() *MockVotingMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockVoting) Accept(ctx context.Context, slug, clientID string, choices []uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, slug, clientID, choices)
	ret0, _ := ret[0].(error)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockVotingMockRecorder) Accept(ctx, slug, clientID, choices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockVoting)(nil).Accept), ctx, slug, clientID, choices)
}

// MockConfigLookup is a mock of ConfigLookup interface.
type MockConfigLookup struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLookupMockRecorder
	isgomock struct{}
}

// MockConfigLookupMockRecorder is the mock recorder for MockConfigLookup.
type MockConfigLookupMockRecorder struct {
	mock *MockConfigLookup
}

// NewMockConfigLookup creates a new mock instance.
func NewMockConfigLookup(ctrl *gomock.Controller) *MockConfigLookup {
	mock := &MockConfigLookup{ctrl: ctrl}
	mock.recorder = &MockConfigLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLookup) EXPECT() *MockConfigLookupMockRecorder {
	return m.recorder
}

// BySlug mocks base method.
func (m *MockConfigLookup) BySlug(slug string) (*pollcfg.HotConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BySlug", slug)
	ret0, _ := ret[0].(*pollcfg.HotConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// BySlug indicates an expected call of BySlug.
func (mr *MockConfigLookupMockRecorder) BySlug(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BySlug", reflect.TypeOf((*MockConfigLookup)(nil).BySlug), slug)
}
