// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockRepo) ListActive(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockRepoMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockRepo)(nil).ListActive), ctx)
}

// MockAgeObserver is a mock of AgeObserver interface.
type MockAgeObserver struct {
	ctrl     *gomock.Controller
	recorder *MockAgeObserverMockRecorder
	isgomock struct{}
}

// MockAgeObserverMockRecorder is the mock recorder for MockAgeObserver.
type MockAgeObserverMockRecorder struct {
	mock *MockAgeObserver
}

// NewMockAgeObserver creates a new mock instance.
func NewMockAgeObserver(ctrl *gomock.Controller) *MockAgeObserver {
	mock := &MockAgeObserver{ctrl: ctrl}
	mock.recorder = &MockAgeObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgeObserver) EXPECT() *MockAgeObserverMockRecorder {
	return m.recorder
}

// SetConfigAge mocks base method.
func (m *MockAgeObserver) SetConfigAge(seconds float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigAge", seconds)
}

// SetConfigAge indicates an expected call of SetConfigAge.
func (mr *MockAgeObserverMockRecorder) SetConfigAge(seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigAge", reflect.TypeOf((*MockAgeObserver)(nil).SetConfigAge), seconds)
}
