// Code generated by MockGen. DO NOT EDIT.
// Source: counting.go
//
// Generated by this command:
//
//	mockgen -source=counting.go -destination=mocks/counting.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"

	pollcfg "github.com/dubter/televote/internal/service/pollcfg"
	vote "github.com/dubter/televote/internal/service/vote"
)

// MockApplier is a mock of Applier interface.
type MockApplier struct {
	ctrl     *gomock.Controller
	recorder *MockApplierMockRecorder
	isgomock struct{}
}

// MockApplierMockRecorder is the mock recorder for MockApplier.
type MockApplierMockRecorder struct {
	mock *MockApplier
}

// NewMockApplier creates a new mock instance.
func NewMockApplier(ctrl *gomock.Controller) *MockApplier {
	mock := &MockApplier{ctrl: ctrl}
	mock.recorder = &MockApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplier) EXPECT() *MockApplierMockRecorder {
	return m.recorder
}

// Cast mocks base method.
func (m *MockApplier) Cast(ctx context.Context, pollID uuid.UUID, shardCount uint16, v vote.VoterID, choices []uint8) (vote.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cast", ctx, pollID, shardCount, v, choices)
	ret0, _ := ret[0].(vote.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cast indicates an expected call of Cast.
func (mr *MockApplierMockRecorder) Cast(ctx, pollID, shardCount, v, choices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cast", reflect.TypeOf((*MockApplier)(nil).Cast), ctx, pollID, shardCount, v, choices)
}

// MockConfigLookup is a mock of ConfigLookup interface.
type MockConfigLookup struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLookupMockRecorder
	isgomock struct{}
}

// MockConfigLookupMockRecorder is the mock recorder for MockConfigLookup.
type MockConfigLookupMockRecorder struct {
	mock *MockConfigLookup
}

// NewMockConfigLookup creates a new mock instance.
func NewMockConfigLookup(ctrl *gomock.Controller) *MockConfigLookup {
	mock := &MockConfigLookup{ctrl: ctrl}
	mock.recorder = &MockConfigLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLookup) EXPECT() *MockConfigLookupMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockConfigLookup) ByID(id uuid.UUID) (*pollcfg.HotConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", id)
	ret0, _ := ret[0].(*pollcfg.HotConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockConfigLookupMockRecorder) ByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockConfigLookup)(nil).ByID), id)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// ApplySeconds mocks base method.
func (m *MockObserver) ApplySeconds(d float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplySeconds", d)
}

// ApplySeconds indicates an expected call of ApplySeconds.
func (mr *MockObserverMockRecorder) ApplySeconds(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySeconds", reflect.TypeOf((*MockObserver)(nil).ApplySeconds), d)
}

// VoteCounted mocks base method.
func (m *MockObserver) VoteCounted(result vote.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteCounted", result)
}

// VoteCounted indicates an expected call of VoteCounted.
func (mr *MockObserverMockRecorder) VoteCounted(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteCounted", reflect.TypeOf((*MockObserver)(nil).VoteCounted), result)
}

// VoteRejected mocks base method.
func (m *MockObserver) VoteRejected(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteRejected", reason)
}

// VoteRejected indicates an expected call of VoteRejected.
func (mr *MockObserverMockRecorder) VoteRejected(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteRejected", reflect.TypeOf((*MockObserver)(nil).VoteRejected), reason)
}
