// Code generated by MockGen. DO NOT EDIT.
// Source: polls.go
//
// Generated by this command:
//
//	mockgen -source=polls.go -destination=mocks/polls.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CloseNow mocks base method.
func (m *MockStore) CloseNow(ctx context.Context, id uuid.UUID, version uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseNow", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseNow indicates an expected call of CloseNow.
func (mr *MockStoreMockRecorder) CloseNow(ctx, id, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseNow", reflect.TypeOf((*MockStore)(nil).CloseNow), ctx, id, version)
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, p *domain.Poll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, p)
}

// GetBySlug mocks base method.
func (m *MockStore) GetBySlug(ctx context.Context, slug string) (*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockStoreMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockStore)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx)
}

// Transition mocks base method.
func (m *MockStore) Transition(ctx context.Context, id uuid.UUID, to domain.Status, version uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, id, to, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transition indicates an expected call of Transition.
func (mr *MockStoreMockRecorder) Transition(ctx, id, to, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockStore)(nil).Transition), ctx, id, to, version)
}

// MockResultStore is a mock of ResultStore interface.
type MockResultStore struct {
	ctrl     *gomock.Controller
	recorder *MockResultStoreMockRecorder
	isgomock struct{}
}

// MockResultStoreMockRecorder is the mock recorder for MockResultStore.
type MockResultStoreMockRecorder struct {
	mock *MockResultStore
}

// NewMockResultStore creates a new mock instance.
func NewMockResultStore(ctrl *gomock.Controller) *MockResultStore {
	mock := &MockResultStore{ctrl: ctrl}
	mock.recorder = &MockResultStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultStore) EXPECT() *MockResultStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockResultStore) Get(ctx context.Context, pollID uuid.UUID) (domain.Aggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pollID)
	ret0, _ := ret[0].(domain.Aggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResultStoreMockRecorder) Get(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResultStore)(nil).Get), ctx, pollID)
}

// MockAuditor is a mock of Auditor interface.
type MockAuditor struct {
	ctrl     *gomock.Controller
	recorder *MockAuditorMockRecorder
	isgomock struct{}
}

// MockAuditorMockRecorder is the mock recorder for MockAuditor.
type MockAuditorMockRecorder struct {
	mock *MockAuditor
}

// NewMockAuditor creates a new mock instance.
func NewMockAuditor(ctrl *gomock.Controller) *MockAuditor {
	mock := &MockAuditor{ctrl: ctrl}
	mock.recorder = &MockAuditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditor) EXPECT() *MockAuditorMockRecorder {
	return m.recorder
}

// Audit mocks base method.
func (m *MockAuditor) Audit(ctx context.Context, actor, action, entity string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Audit", ctx, actor, action, entity, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Audit indicates an expected call of Audit.
func (mr *MockAuditorMockRecorder) Audit(ctx, actor, action, entity, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Audit", reflect.TypeOf((*MockAuditor)(nil).Audit), ctx, actor, action, entity, payload)
}
