// Code generated by MockGen. DO NOT EDIT.
// Source: advisor.go
//
// Generated by this command:
//
//	mockgen -source=advisor.go -destination=mocks/advisor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPolls is a mock of Polls interface.
type MockPolls struct {
	ctrl     *gomock.Controller
	recorder *MockPollsMockRecorder
	isgomock struct{}
}

// MockPollsMockRecorder is the mock recorder for MockPolls.
type MockPollsMockRecorder struct {
	mock *MockPolls
}

// NewMockPolls creates a new mock instance.
func NewMockPolls(ctrl *gomock.Controller) *MockPolls {
	mock := &MockPolls{ctrl: ctrl}
	mock.recorder = &MockPollsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolls) EXPECT() *MockPollsMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockPolls) ListActive(ctx context.Context) ([]*domain.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]*domain.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockPollsMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockPolls)(nil).ListActive), ctx)
}

// MockLag is a mock of Lag interface.
type MockLag struct {
	ctrl     *gomock.Controller
	recorder *MockLagMockRecorder
	isgomock struct{}
}

// MockLagMockRecorder is the mock recorder for MockLag.
type MockLagMockRecorder struct {
	mock *MockLag
}

// NewMockLag creates a new mock instance.
func NewMockLag(ctrl *gomock.Controller) *MockLag {
	mock := &MockLag{ctrl: ctrl}
	mock.recorder = &MockLagMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLag) EXPECT() *MockLagMockRecorder {
	return m.recorder
}

// Lag mocks base method.
func (m *MockLag) Lag(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lag", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lag indicates an expected call of Lag.
func (mr *MockLagMockRecorder) Lag(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lag", reflect.TypeOf((*MockLag)(nil).Lag), ctx)
}
