// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/redis/rueidis (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks/redis.go -package=mocks github.com/redis/rueidis Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	rueidis "github.com/redis/rueidis"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// B mocks base method.
func (m *MockClient) B() rueidis.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "B")
	ret0, _ := ret[0].(rueidis.Builder)
	return ret0
}

// B indicates an expected call of B.
func (mr *MockClientMockRecorder) B() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "B", reflect.TypeOf((*MockClient)(nil).B))
}

// Close mocks base method.
func (m *MockClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Dedicate mocks base method.
func (m *MockClient) Dedicate() (rueidis.DedicatedClient, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dedicate")
	ret0, _ := ret[0].(rueidis.DedicatedClient)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// Dedicate indicates an expected call of Dedicate.
func (mr *MockClientMockRecorder) Dedicate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dedicate", reflect.TypeOf((*MockClient)(nil).Dedicate))
}

// Dedicated mocks base method.
func (m *MockClient) Dedicated(fn func(rueidis.DedicatedClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dedicated", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dedicated indicates an expected call of Dedicated.
func (mr *MockClientMockRecorder) Dedicated(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dedicated", reflect.TypeOf((*MockClient)(nil).Dedicated), fn)
}

// Do mocks base method.
func (m *MockClient) Do(ctx context.Context, cmd rueidis.Completed) rueidis.RedisResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, cmd)
	ret0, _ := ret[0].(rueidis.RedisResult)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockClientMockRecorder) Do(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockClient)(nil).Do), ctx, cmd)
}

// DoCache mocks base method.
func (m *MockClient) DoCache(ctx context.Context, cmd rueidis.Cacheable, ttl time.Duration) rueidis.RedisResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoCache", ctx, cmd, ttl)
	ret0, _ := ret[0].(rueidis.RedisResult)
	return ret0
}

// DoCache indicates an expected call of DoCache.
func (mr *MockClientMockRecorder) DoCache(ctx, cmd, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoCache", reflect.TypeOf((*MockClient)(nil).DoCache), ctx, cmd, ttl)
}

// DoMulti mocks base method.
func (m *MockClient) DoMulti(ctx context.Context, multi ...rueidis.Completed) []rueidis.RedisResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range multi {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DoMulti", varargs...)
	ret0, _ := ret[0].([]rueidis.RedisResult)
	return ret0
}

// DoMulti indicates an expected call of DoMulti.
func (mr *MockClientMockRecorder) DoMulti(ctx any, multi ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, multi...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoMulti", reflect.TypeOf((*MockClient)(nil).DoMulti), varargs...)
}

// DoMultiCache mocks base method.
func (m *MockClient) DoMultiCache(ctx context.Context, multi ...rueidis.CacheableTTL) []rueidis.RedisResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range multi {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DoMultiCache", varargs...)
	ret0, _ := ret[0].([]rueidis.RedisResult)
	return ret0
}

// DoMultiCache indicates an expected call of DoMultiCache.
func (mr *MockClientMockRecorder) DoMultiCache(ctx any, multi ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, multi...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoMultiCache", reflect.TypeOf((*MockClient)(nil).DoMultiCache), varargs...)
}

// DoMultiStream mocks base method.
func (m *MockClient) DoMultiStream(ctx context.Context, multi ...rueidis.Completed) rueidis.MultiRedisResultStream {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range multi {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DoMultiStream", varargs...)
	ret0, _ := ret[0].(rueidis.MultiRedisResultStream)
	return ret0
}

// DoMultiStream indicates an expected call of DoMultiStream.
func (mr *MockClientMockRecorder) DoMultiStream(ctx any, multi ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, multi...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoMultiStream", reflect.TypeOf((*MockClient)(nil).DoMultiStream), varargs...)
}

// DoStream mocks base method.
func (m *MockClient) DoStream(ctx context.Context, cmd rueidis.Completed) rueidis.RedisResultStream {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoStream", ctx, cmd)
	ret0, _ := ret[0].(rueidis.RedisResultStream)
	return ret0
}

// DoStream indicates an expected call of DoStream.
func (mr *MockClientMockRecorder) DoStream(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStream", reflect.TypeOf((*MockClient)(nil).DoStream), ctx, cmd)
}

// Mode mocks base method.
func (m *MockClient) Mode() rueidis.ClientMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mode")
	ret0, _ := ret[0].(rueidis.ClientMode)
	return ret0
}

// Mode indicates an expected call of Mode.
func (mr *MockClientMockRecorder) Mode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mode", reflect.TypeOf((*MockClient)(nil).Mode))
}

// Nodes mocks base method.
func (m *MockClient) Nodes() map[string]rueidis.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nodes")
	ret0, _ := ret[0].(map[string]rueidis.Client)
	return ret0
}

// Nodes indicates an expected call of Nodes.
func (mr *MockClientMockRecorder) Nodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockClient)(nil).Nodes))
}

// Receive mocks base method.
func (m *MockClient) Receive(ctx context.Context, subscribe rueidis.Completed, fn func(rueidis.PubSubMessage)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, subscribe, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Receive indicates an expected call of Receive.
func (mr *MockClientMockRecorder) Receive(ctx, subscribe, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockClient)(nil).Receive), ctx, subscribe, fn)
}
