// Code generated by MockGen. DO NOT EDIT.
// Source: voting.go
//
// Generated by this command:
//
//	mockgen -source=voting.go -destination=mocks/voting.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/dubter/televote/internal/domain"
	pollcfg "github.com/dubter/televote/internal/service/pollcfg"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigLookup is a mock of ConfigLookup interface.
type MockConfigLookup struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLookupMockRecorder
	isgomock struct{}
}

// MockConfigLookupMockRecorder is the mock recorder for MockConfigLookup.
type MockConfigLookupMockRecorder struct {
	mock *MockConfigLookup
}

// NewMockConfigLookup creates a new mock instance.
func NewMockConfigLookup(ctrl *gomock.Controller) *MockConfigLookup {
	mock := &MockConfigLookup{ctrl: ctrl}
	mock.recorder = &MockConfigLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLookup) EXPECT() *MockConfigLookupMockRecorder {
	return m.recorder
}

// BySlug mocks base method.
func (m *MockConfigLookup) BySlug(slug string) (*pollcfg.HotConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BySlug", slug)
	ret0, _ := ret[0].(*pollcfg.HotConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// BySlug indicates an expected call of BySlug.
func (mr *MockConfigLookupMockRecorder) BySlug(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BySlug", reflect.TypeOf((*MockConfigLookup)(nil).BySlug), slug)
}

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m_2 *MockSink) Send(ctx context.Context, m domain.VoteMessage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Send", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSinkMockRecorder) Send(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSink)(nil).Send), ctx, m)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// ProduceSeconds mocks base method.
func (m *MockObserver) ProduceSeconds(d float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProduceSeconds", d)
}

// ProduceSeconds indicates an expected call of ProduceSeconds.
func (mr *MockObserverMockRecorder) ProduceSeconds(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceSeconds", reflect.TypeOf((*MockObserver)(nil).ProduceSeconds), d)
}

// VoteAccepted mocks base method.
func (m *MockObserver) VoteAccepted() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteAccepted")
}

// VoteAccepted indicates an expected call of VoteAccepted.
func (mr *MockObserverMockRecorder) VoteAccepted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteAccepted", reflect.TypeOf((*MockObserver)(nil).VoteAccepted))
}

// VoteRejected mocks base method.
func (m *MockObserver) VoteRejected(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteRejected", reason)
}

// VoteRejected indicates an expected call of VoteRejected.
func (mr *MockObserverMockRecorder) VoteRejected(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteRejected", reflect.TypeOf((*MockObserver)(nil).VoteRejected), reason)
}
